import Link from "next/link";
import { AdminHeader } from "@/components/admin/admin-header";
import { CreateJobForm } from "@/components/admin/create-job-form";
import { listAdminJobs } from "@/lib/jobs/admin";

export default async function AdminJobsPage({ searchParams }: { searchParams: Promise<{ created?: string }> }) {
  const [{ created }, { jobs, error }] = await Promise.all([searchParams, listAdminJobs()]);
  return <><AdminHeader /><main className="mx-auto max-w-6xl px-6 py-12"><div className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_24rem]"><section><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-indigo-600">Admin</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Job openings</h1></div></div>{created ? <p className="mt-5 rounded-lg bg-emerald-50 px-4 py-3 text-sm text-emerald-800">Job opening created.</p> : null}{error ? <p className="mt-5 rounded-lg bg-rose-50 px-4 py-3 text-sm text-rose-800" role="alert">{error}</p> : null}<div className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{!error && jobs.length === 0 ? <p className="px-6 py-12 text-center text-slate-600">No job openings yet. Create the first one using the form.</p> : jobs.map((job) => <article className="flex flex-col gap-4 border-b border-slate-100 px-6 py-5 last:border-b-0 sm:flex-row sm:items-center sm:justify-between" key={job.id}><div><h2 className="font-semibold text-slate-950">{job.title}</h2><p className="mt-1 text-sm text-slate-600">{job.company} · {new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(job.createdAt))}</p><p className="mt-2 text-sm text-slate-500">{job.applicationCount} application{job.applicationCount === 1 ? "" : "s"}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold uppercase ${job.status === "open" ? "bg-emerald-100 text-emerald-800" : "bg-slate-200 text-slate-700"}`}>{job.status}</span><Link className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-800 hover:bg-slate-50" href={`/admin/jobs/${job.id}`}>View</Link></div></article>)}</div></section><aside><h2 className="text-xl font-semibold text-slate-950">Create job</h2><p className="mt-2 text-sm leading-6 text-slate-600">New jobs are open by default and will be available to the public flow in a later phase.</p><div className="mt-5"><CreateJobForm /></div></aside></div></main></>;
}
