"use client";
import { useActionState, useState } from "react";
import { submitApplicationAction } from "@/app/jobs/[jobId]/actions";
import type { ApplicationSubmissionResult } from "@/lib/applications/public";
import { MAX_RESUME_SIZE_BYTES, MAX_RESUME_SIZE_LABEL } from "@/lib/resumes/constants";
const initialState: ApplicationSubmissionResult = { error: null };
export function ApplicationForm({ jobId }: { jobId: string }) {
  const submitForJob = submitApplicationAction.bind(null, jobId);
  const [state, formAction, pending] = useActionState(submitForJob, initialState);
  const [clientResumeError, setClientResumeError] = useState<string | null>(null);
  const validateResume = (file: File | null) => !file ? "A resume is required." : !file.name.toLowerCase().endsWith(".docx") ? "Please select a Microsoft Word (.docx) file." : file.size === 0 ? "The resume file is empty." : file.size > MAX_RESUME_SIZE_BYTES ? `The resume must be ${MAX_RESUME_SIZE_LABEL} or smaller.` : null;
  return <form action={formAction} className="mt-8 space-y-5" onSubmit={(event) => { const resume = new FormData(event.currentTarget).get("resume"); const error = resume instanceof File ? validateResume(resume) : "A resume is required."; setClientResumeError(error); if (error) event.preventDefault(); }}><div className="grid gap-5 sm:grid-cols-2"><Field errors={state.fieldErrors?.fullName} label="Full name" name="fullName" /><Field errors={state.fieldErrors?.phone} label="Phone number" name="phone" /><Field errors={state.fieldErrors?.email} label="Email address" name="email" type="email" /><Field errors={state.fieldErrors?.age} label="Age" name="age" type="number" min="16" max="100" /><div className="sm:col-span-2"><Field errors={state.fieldErrors?.address} label="Address" name="address" /></div><div className="sm:col-span-2"><Field errors={state.fieldErrors?.currentLocation} label="Current location / place" name="currentLocation" /></div></div><div><label className="block text-sm font-semibold text-slate-800" htmlFor="resume">Resume (.docx only)</label><input accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className="mt-2 block w-full text-sm text-slate-700 file:mr-4 file:rounded-lg file:border-0 file:bg-slate-100 file:px-3 file:py-2 file:text-sm file:font-semibold file:text-slate-800" id="resume" name="resume" onChange={(event) => setClientResumeError(validateResume(event.target.files?.[0] ?? null))} required type="file" /><p className="mt-2 text-xs text-slate-500">DOCX only, up to {MAX_RESUME_SIZE_LABEL}. The file is checked again securely on submission.</p><FieldError errors={clientResumeError ? [clientResumeError] : state.fieldErrors?.resume} /></div>{state.error ? <p className="rounded-lg bg-rose-50 px-4 py-3 text-sm text-rose-800" role="alert">{state.error}</p> : null}<button className="rounded-lg bg-slate-950 px-5 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-60" disabled={pending} type="submit">{pending ? "Submitting application…" : "Submit application"}</button></form>;
}
function Field({ label, name, type = "text", min, max, errors }: { label: string; name: string; type?: string; min?: string; max?: string; errors?: string[] }) {
  return <div><label className="block text-sm font-semibold text-slate-800" htmlFor={name}>{label}</label><input className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5 outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100" id={name} max={max} min={min} name={name} required type={type} /><FieldError errors={errors} /></div>;
}
function FieldError({ errors }: { errors?: string[] | null }) { return errors?.[0] ? <p className="mt-1.5 text-sm text-rose-700">{errors[0]}</p> : null; }
